### ISSUE TITLE
下载 ffmpeg 报错

### ISSUE THREAD

**Issue by HolmesZhao** [helson-lin/ffandown#2]
docker 环境已经设置了代理, 还是会报这个错误, 在容器内使用 curl 下载这个 zip 是成功的
```shell
[ffdown]  downloading ffmpeg:https://nn.oimi.space/https://github.com/ffbinaries/ffbinaries-prebuilt/releases/download/
v4.4.1/ffmpeg-4.4.1-linux-64.zip                                                                                       
download Failed GotError [RequestError]: read ECONNRESET                                                               
    at ClientRequest.<anonymous> (/snapshot/ffandown/node_modules/.pnpm/registry.npmmirror.com+got@8.3.2/node_modules/g
ot/index.js:182:22)                                                                                                    
    at Object.onceWrapper (events.js:520:26)                                                                           
    at ClientRequest.emit (events.js:400:28)                                                                           
    at TLSSocket.socketErrorListener (_http_client.js:475:9)                                                           
    at TLSSocket.emit (events.js:400:28)                                                                               
    at emitErrorNT (internal/streams/destroy.js:106:8)                                                                 
    at emitErrorCloseNT (internal/streams/destroy.js:74:3)                                                             
    at processTicksAndRejections (internal/process/task_queues.js:82:21) {                                             
  code: 'ECONNRESET',                                                                                                  
  host: 'nn.oimi.space',                                                                                               
  hostname: 'nn.oimi.space',                                                                                           
  method: 'GET',                                                                                                       
  path: '/https://github.com/ffbinaries/ffbinaries-prebuilt/releases/download/v4.4.1/ffmpeg-4.4.1-linux-64.zip',       
  protocol: 'https:',                                                                                                  
  url: 'https://nn.oimi.space/https://github.com/ffbinaries/ffbinaries-prebuilt/releases/download/v4.4.1/ffmpeg-4.4.1-l
inux-64.zip'                                                                                                           
} 
```

**Comment by helson-lin** [comment]
这个不需要代理的 https://nn.oimi.space/是github的加速服务，cloudfalre的托管的，免费的worker有限制。

**Comment by HolmesZhao** [comment]
> 理的 [https://nn.oimi.space/是github的加速服务，cloudfalre的托管的，免费的worker有限制。你先关闭代理试试看，我后面把ffmpeg文件托](https://nn.oimi.space/%E6%98%AFgithub%E7%9A%84%E5%8A%A0%E9%80%9F%E6%9C%8D%E5%8A%A1%EF%BC%8Ccloudfalre%E7%9A%84%E6%89%98%E7%AE%A1%E7%9A%84%EF%BC%8C%E5%85%8D%E8%B4%B9%E7%9A%84worker%E6%9C%89%E9%99%90%E5%88%B6%E3%80%82%E4%BD%A0%E5%85%88%E5%85%B3%E9%97%AD%E4%BB%A3%E7%90%86%E8%AF%95%E8%AF%95%E7%9C%8B%EF%BC%8C%E6%88%91%E5%90%8E%E9%9D%A2%E6%8A%8Affmpeg%E6%96%87%E4%BB%B6%E6%89%98%E7%AE%A1%E5%88%B0%E5%9B%BD%E5%86%85oss)

就是因为不开代理也失败😂所以也尝试了开代理, 还是失败

**Comment by helson-lin** [comment]
> > 理的 [https://nn.oimi.space/是github的加速服务，cloudfalre的托管的，免费的worker有限制。你先关闭代理试试看，我后面把ffmpeg文件托](https://nn.oimi.space/%E6%98%AFgithub%E7%9A%84%E5%8A%A0%E9%80%9F%E6%9C%8D%E5%8A%A1%EF%BC%8Ccloudfalre%E7%9A%84%E6%89%98%E7%AE%A1%E7%9A%84%EF%BC%8C%E5%85%8D%E8%B4%B9%E7%9A%84worker%E6%9C%89%E9%99%90%E5%88%B6%E3%80%82%E4%BD%A0%E5%85%88%E5%85%B3%E9%97%AD%E4%BB%A3%E7%90%86%E8%AF%95%E8%AF%95%E7%9C%8B%EF%BC%8C%E6%88%91%E5%90%8E%E9%9D%A2%E6%8A%8Affmpeg%E6%96%87%E4%BB%B6%E6%89%98%E7%AE%A1%E5%88%B0%E5%9B%BD%E5%86%85oss)
> 
> 就是因为不开代理也失败😂所以也尝试了开代理, 还是失败

Cloudflare可能不太稳定,毕竟是免费的,我找时间明天做一下修复,走国内oss

**Comment by helson-lin** [comment]
> ![image](https://user-images.githubusercontent.com/19728934/232357291-1bc59f12-c7a8-47a4-9bdf-4b55fa36bbd5.png) 我手动下载 ffmpeg 后放到 `/app/lib` 下, 能跑了, 但是下载还会报错, 上面的错误, 我的环境是群晖的 docker

我群晖docker测试过的，具体原因还不清楚，我更新了docker镜像，你重新拉去最新latest的镜像试试，不需要代理的。我换了国内的OSS

**Comment by HolmesZhao** [comment]
> > ![image](https://user-images.githubusercontent.com/19728934/232357291-1bc59f12-c7a8-47a4-9bdf-4b55fa36bbd5.png) 我手动下载 ffmpeg 后放到 `/app/lib` 下, 能跑了, 但是下载还会报错, 上面的错误, 我的环境是群晖的 docker
> 
> 我群晖docker测试过的，具体原因还不清楚，我更新了docker镜像，你重新拉去最新latest的镜像试试，不需要代理的。我换了国内的OSS

![image](https://user-images.githubusercontent.com/19728934/232361138-5a2388af-3d78-4c01-9cff-4ed0e014bc9b.png)
是的, 我看已经是国内镜像了, 下载很快, 但是下载 m3u8 视频的时候会报错误
是这个链接:
`https://bitdash-a.akamaihd.net/content/sintel/hls/playlist.m3u8`

**Comment by HolmesZhao** [comment]
还有可以考虑提供一下下载设置 http/https 代理的能力, 毕竟有的 m3u8 视频时国外的地址

**Comment by helson-lin** [comment]
> 还有可以考虑提供一下下载设置 http/https 代理的能力, 毕竟有的 m3u8 视频时国外的地址

可以的，最新的镜像可以正常下载了嘛

**Comment by helson-lin** [comment]
> > > 还有可以考虑提供一下下载设置 http/https 代理的能力, 毕竟有的 m3u8 视频时国外的地址
> > 
> > 
> > 可以的，最新的镜像可以正常下载了嘛
> 
> 可以正常下载 ffmpeg 了, 但是下载 m3u8 视频报错

权限问题有的网站做了检验，我晚点处理一下

**Comment by helson-lin** [comment]
> > > > > 还有可以考虑提供一下下载设置 http/https 代理的能力, 毕竟有的 m3u8 视频时国外的地址
> > > > 
> > > > 
> > > > 可以的，最新的镜像可以正常下载了嘛
> > > 
> > > 
> > > 可以正常下载 ffmpeg 了, 但是下载 m3u8 视频报错
> > 
> > 
> > 权限问题有的网站做了检验，我晚点处理一下
> 
> 期待大佬的修改~
> 
> 1. 需要支持挂代理
> 2. 下载视频错误问题, 感谢

你给的地址问题下载403已经修复，稍后更新，代理问题后续添加

**Comment by helson-lin** [comment]
> > > > > 还有可以考虑提供一下下载设置 http/https 代理的能力, 毕竟有的 m3u8 视频时国外的地址
> > > > 
> > > > 
> > > > 可以的，最新的镜像可以正常下载了嘛
> > > 
> > > 
> > > 可以正常下载 ffmpeg 了, 但是下载 m3u8 视频报错
> > 
> > 
> > 权限问题有的网站做了检验，我晚点处理一下
> 
> 期待大佬的修改~
> 
> 1. 需要支持挂代理
> 2. 下载视频错误问题, 感谢

麻烦获取最新image看看，我这边测试没有问题，麻烦反馈一下 没有问题我这边close issue

**Comment by helson-lin** [comment]
> 我看日志里面有输出env，我给的htttps_proxy也能读到，但是还没用是么？

你给我一个需要代理的地址 我测试一下，后面我直接在项目内集成代理配置

**Comment by HolmesZhao** [comment]
> > 我看日志里面有输出env，我给的htttps_proxy也能读到，但是还没用是么？
> 
> 你给我一个需要代理的地址 我测试一下，后面我直接在项目内集成代理配置

理论上https://zaza-po.mushroomtrack.com/hls/2LKC17DlTLQ6vviDE7rN8w/1681752415/27000/27104/27104.m3u8这个是需要的，这个URL我是在一个需要翻墙的网页爬🉐

**Comment by helson-lin** [comment]
> > > 我看日志里面有输出env，我给的htttps_proxy也能读到，但是还没用是么？
> > 
> > 
> > 你给我一个需要代理的地址 我测试一下，后面我直接在项目内集成代理配置
> 
> 理论上[https://zaza-po.mushroomtrack.com/hls/2LKC17DlTLQ6vviDE7rN8w/1681752415/27000/27104/27104.m3u8这个是需要的，这个URL我是在一个需要翻墙的网页爬🉐](https://zaza-po.mushroomtrack.com/hls/2LKC17DlTLQ6vviDE7rN8w/1681752415/27000/27104/27104.m3u8%E8%BF%99%E4%B8%AA%E6%98%AF%E9%9C%80%E8%A6%81%E7%9A%84%EF%BC%8C%E8%BF%99%E4%B8%AAURL%E6%88%91%E6%98%AF%E5%9C%A8%E4%B8%80%E4%B8%AA%E9%9C%80%E8%A6%81%E7%BF%BB%E5%A2%99%E7%9A%84%E7%BD%91%E9%A1%B5%E7%88%AC%F0%9F%89%90)

我测试了 我这边这正常下载你的这个地址，你别设置代理，关闭试试看，不知道是不是你代理问题

**Comment by HolmesZhao** [comment]
> > > > 我看日志里面有输出env，我给的htttps_proxy也能读到，但是还没用是么？
> > > 
> > > 
> > > 你给我一个需要代理的地址 我测试一下，后面我直接在项目内集成代理配置
> > 
> > 
> > 理论上[https://zaza-po.mushroomtrack.com/hls/2LKC17DlTLQ6vviDE7rN8w/1681752415/27000/27104/27104.m3u8这个是需要的，这个URL我是在一个需要翻墙的网页爬🉐](https://zaza-po.mushroomtrack.com/hls/2LKC17DlTLQ6vviDE7rN8w/1681752415/27000/27104/27104.m3u8%E8%BF%99%E4%B8%AA%E6%98%AF%E9%9C%80%E8%A6%81%E7%9A%84%EF%BC%8C%E8%BF%99%E4%B8%AAURL%E6%88%91%E6%98%AF%E5%9C%A8%E4%B8%80%E4%B8%AA%E9%9C%80%E8%A6%81%E7%BF%BB%E5%A2%99%E7%9A%84%E7%BD%91%E9%A1%B5%E7%88%AC%F0%9F%89%90)
> 
> 我测试了 我这边这正常下载你的这个地址，你别设置代理，关闭试试看，不知道是不是你代理问题

😲我试一下

**Comment by HolmesZhao** [comment]
![IMG_0334](https://user-images.githubusercontent.com/19728934/232521706-a67c352b-9795-4023-9a4c-708896b4e0e2.png)

**Comment by HolmesZhao** [comment]
还有就是我的群晖，下载好慢啊，https://bitdash-a.akamaihd.net/content/sintel/hls/playlist.m3u8 这个一分钟居然才下载2mb

**Comment by helson-lin** [comment]
> https://bitdash-a.akamaihd.net/content/sintel/hls/playlist.m3u8

我这边你这个地址每秒5MB/s黑裙

**Comment by HolmesZhao** [comment]
> > https://bitdash-a.akamaihd.net/content/sintel/hls/playlist.m3u8
> 
> 我这边你这个地址每秒5MB/s黑裙

我明天再用电脑试试，这个问题是解决了，可以关了🥲另外一个错误辛苦大佬了

**Comment by HolmesZhao** [comment]
> > ![IMG_0334](https://user-images.githubusercontent.com/19728934/232521706-a67c352b-9795-4023-9a4c-708896b4e0e2.png)
> > 报错，代理关了
> > ![](https://user-images.githubusercontent.com/84565447/232525653-14c56e63-93dc-4afa-8e43-68d561e0bb5e.png)
> 
> 你的这个地址我也没正常下载 我感觉是网络问题，你是桥接网络还是host直通的。这个速度比较慢应该是服务端的问题

我是桥接的

**Comment by GitHubmnxz** [comment]
stdout: Master 1 is running
stdout: [ffdown]  downloading ffmpeg:https://pic.kblue.site/ffmpeg-4.4.1-linux-64.zip
stdout: [ffandown] server running at:
stdout: 
stdout:     - http://127.0.0.1:8081/
stdout:     - http://172.17.0.9:8081/
stdout: /app/lib/ffmpeg [ '-formats' ] {
stdout:   captureStdout: true,
stdout:   stdoutLines: 0,
stdout:   env: {
stdout:     FFMPEG_PATH: '/app/lib/ffmpeg',
stdout:     HOME: '/root',
stdout:     HOSTNAME: 'DownMp4Down',
stdout:     PATH: '/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin',
stdout:     PKG_EXECPATH: '/app/ffandown-linux'
stdout:   }
stdout: }
stdout: exit:0null
stdout: /app/lib/ffmpeg [ '-encoders' ] {
stdout:   captureStdout: true,
stdout:   stdoutLines: 0,
stdout:   env: {
stdout:     FFMPEG_PATH: '/app/lib/ffmpeg',
stdout:     HOME: '/root',
stdout:     HOSTNAME: 'DownMp4Down',
stdout:     PATH: '/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin',
stdout:     PKG_EXECPATH: '/app/ffandown-linux'
stdout:   }
stdout: }
stdout: exit:0null
stdout: /app/lib/ffmpeg [
stdout:   '-user_agent',
stdout:   'Mozilla/5.0 (Macintosh; Intel Mac OS X 11_1_0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/88.0.4324.182 Safari/537.36',
stdout:   '-referer',
stdout:   'https://bitdash-a.akamaihd.net/',
stdout:   '-i',
stdout:   'https://bitdash-a.akamaihd.net/content/sintel/hls/playlist.m3u8',
stdout:   '-y',
stdout:   '-threads',
stdout:   '4',
stdout:   '-preset',
stdout:   'ultrafast',
stdout:   '-c:v',
stdout:   'copy',
stdout:   '-bsf:a',
stdout:   'aac_adtstoasc',
stdout:   '/app/media/1231231.mp4'
stdout: ] {
stdout:   captureStdout: true,
stdout:   niceness: 0,
stdout:   cwd: undefined,
stdout:   env: {
stdout:     FFMPEG_PATH: '/app/lib/ffmpeg',
stdout:     HOME: '/root',
stdout:     HOSTNAME: 'DownMp4Down',
stdout:     PATH: '/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin',
stdout:     PKG_EXECPATH: '/app/ffandown-linux'
stdout:   }
stdout: }
stdout: exit:nullSIGSEGV
stdout: 下载失败 
stdout: 下载失败：Error: Error: ffmpeg was killed with signal SIGSEGV
 
环境是openwrt里面的docker
有没有办法解决哦！！！

**Comment by helson-lin** [comment]
> https://bitdash-a.akamaihd.net/content/sintel/hls/playlist.m3u8

请问系统配置是什么：intel还是arm主机还是其他平台

**Comment by GitHubmnxz** [comment]
> 
intel j3455  
Openwrt5.4.188 UEFI引导 iStoreOS 21.02.3 2023040712

**Comment by HolmesZhao** [comment]
我用 m1 mac 跑的时候报错
```
info: 2023-04-19 20:49:55: 	Setting FFMPEG_PATH:/Users/zwy/Downloads/yuwen/lib/ffmpeg
info: 2023-04-19 20:49:55: 	[ffandown] server running at port: 8081
info: 2023-04-19 20:49:59: 	online m3u8 url: https://zaza-po.mushroomtrack.com/hls/2LKC17DlTLQ6vviDE7rN8w/1681752415/27000/27104/27104.m3u8, file download path:  /Users/zwy/Downloads/yuwen/media/1111.mp4
info: 2023-04-19 20:50:02: 	1111.mp4, Error: Error: ffmpeg exited with code 1: https://zaza-po.mushroomtrack.com/hls/2LKC17DlTLQ6vviDE7rN8w/1681752415/27000/27104/27104.m3u8: Server returned 4XX Client Error, but not one of 40{0,1,3,4}
```

**Comment by helson-lin** [comment]
> https://zaza-po.mushroomtrack.com/hls/2LKC17DlTLQ6vviDE7rN8w/1681752415/27000/27104/27104.m3u8

你的这个地址你测试了吗，我用INNA无法播放，其他软件也是，应该是地址问题，我开发的笔记本就是m1 mac

**Comment by HolmesZhao** [comment]
> > https://bitdash-a.akamaihd.net/content/sintel/hls/playlist.m3u8
> 
> 请问系统配置是什么：intel还是arm主机还是其他平台

这个url我 intel , 白群晖, 没报错了就是网速特别慢🤣

**Comment by HolmesZhao** [comment]
X

> https://zaza-po.mushroomtrack.com/hls/2LKC17DlTLQ6vviDE7rN8w/1681752415/27000/27104/27104.m3u8

这个地址居然会变😂我再去搞一个 `https://zara-molo.mushroomtrack.com/hls/fxdpEpExTlwiq0vgczVXKA/1681919645/27000/27104/27104.m3u8`

**Comment by HolmesZhao** [comment]
> X
> 
> > https://zaza-po.mushroomtrack.com/hls/2LKC17DlTLQ6vviDE7rN8w/1681752415/27000/27104/27104.m3u8
> 
> 这个地址居然会变😂我再去搞一个 `https://zara-molo.mushroomtrack.com/hls/fxdpEpExTlwiq0vgczVXKA/1681919645/27000/27104/27104.m3u8`

成功了, 看来还是地址问题😂感谢大佬, 我关闭了哈

**Comment by HolmesZhao** [comment]
> > X
> > > https://zaza-po.mushroomtrack.com/hls/2LKC17DlTLQ6vviDE7rN8w/1681752415/27000/27104/27104.m3u8
> > 
> > 
> > 这个地址居然会变😂我再去搞一个 `https://zara-molo.mushroomtrack.com/hls/fxdpEpExTlwiq0vgczVXKA/1681919645/27000/27104/27104.m3u8`
> 
> 成功了, 看来还是地址问题😂感谢大佬, 我关闭了哈

我群晖的还是有问题, 回去升级一下 docker 镜像再试试试看

**Comment by helson-lin** [comment]
> > X
> > > https://zaza-po.mushroomtrack.com/hls/2LKC17DlTLQ6vviDE7rN8w/1681752415/27000/27104/27104.m3u8
> > 
> > 
> > 这个地址居然会变😂我再去搞一个 `https://zara-molo.mushroomtrack.com/hls/fxdpEpExTlwiq0vgczVXKA/1681919645/27000/27104/27104.m3u8`
> 
> 成功了, 看来还是地址问题😂感谢大佬, 我关闭了哈

有其他问题可以直接加我微信Helson9709
