### ISSUE TITLE
docker启动报错  是访问这个加速地址访问不到吗  

### ISSUE THREAD

**Issue by DingQi1888** [helson-lin/ffandown#28]
███████╗███████╗ █████╗ ███╗   ██╗██████╗  ██████╗ ██╗    ██╗███╗   ██╗
██╔════╝██╔════╝██╔══██╗████╗  ██║██╔══██╗██╔═══██╗██║    ██║████╗  ██║
█████╗  █████╗  ███████║██╔██╗ ██║██║  ██║██║   ██║██║ █╗ ██║██╔██╗ ██║
██╔══╝  ██╔══╝  ██╔══██║██║╚██╗██║██║  ██║██║   ██║██║███╗██║██║╚██╗██║
██║     ██║     ██║  ██║██║ ╚████║██████╔╝╚██████╔╝╚███╔███╔╝██║ ╚████║
╚═╝     ╚═╝     ╚═╝  ╚═╝╚═╝  ╚═══╝╚═════╝  ╚═════╝  ╚══╝╚══╝ ╚═╝  ╚═══╝

[ffandown] ffmpeg: 环境变量设置成功
[ffandown] ffprobe: 环境变量设置成功
Database synced successfully
/snapshot/ffandown/node_modules/.pnpm/got@8.3.2/node_modules/got/index.js:182
                                ee.emit('error', new got.RequestError(err, opts));
                                                 ^

GotError [RequestError]: read ECONNRESET
    at ClientRequest.<anonymous> (/snapshot/ffandown/node_modules/.pnpm/got@8.3.2/node_modules/got/index.js:182:22)
    at Object.onceWrapper (node:events:642:26)
    at ClientRequest.emit (node:events:527:28)
    at TLSSocket.socketErrorListener (node:_http_client:454:9)
    at TLSSocket.emit (node:events:527:28)
    at emitErrorNT (node:internal/streams/destroy:157:8)
    at emitErrorCloseNT (node:internal/streams/destroy:122:3)
    at processTicksAndRejections (node:internal/process/task_queues:83:21) {
  code: 'ECONNRESET',
  host: 'nn.oimi.space',
  hostname: 'nn.oimi.space',
  method: 'GET',
  path: '/https://github.com/helson-lin/ffandown-front/releases/download/v0.0.7/ffandown-frontend.zip',
  protocol: 'https:',
  url: 'https://nn.oimi.space/https://github.com/helson-lin/ffandown-front/releases/download/v0.0.7/ffandown-frontend.zip'
}
docker启动报错  是访问这个加速地址访问不到吗

**Comment by helson-lin** [comment]
对的，你的网络无法正确请求到前端的版本文件。如果网络不行 可以自行吧目录映射出来，然后手动下载上传到目录内。 目录名称为： public 
---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 发送日期 | 2024年03月28日 17:40 |
| 收件人 | ***@***.***> |
| 抄送人 | ***@***.***> |
| 主题 | [helson-lin/ffandown] docker启动报错 是访问这个加速地址访问不到吗 (Issue #28) |

███████╗███████╗ █████╗ ███╗ ██╗██████╗ ██████╗ ██╗ ██╗███╗ ██╗
██╔════╝██╔════╝██╔══██╗████╗ ██║██╔══██╗██╔═══██╗██║ ██║████╗ ██║
█████╗ █████╗ ███████║██╔██╗ ██║██║ ██║██║ ██║██║ █╗ ██║██╔██╗ ██║
██╔══╝ ██╔══╝ ██╔══██║██║╚██╗██║██║ ██║██║ ██║██║███╗██║██║╚██╗██║
██║ ██║ ██║ ██║██║ ╚████║██████╔╝╚██████╔╝╚███╔███╔╝██║ ╚████║
╚═╝ ╚═╝ ╚═╝ ╚═╝╚═╝ ╚═══╝╚═════╝ ╚═════╝ ╚══╝╚══╝ ╚═╝ ╚═══╝

[ffandown] ffmpeg: 环境变量设置成功
[ffandown] ffprobe: 环境变量设置成功
Database synced successfully
***@***.***/node_modules/got/index.js:182
ee.emit('error', new got.RequestError(err, opts));
^

GotError [RequestError]: read ECONNRESET
at ClientRequest. ***@***.***/node_modules/got/index.js:182:22)
at Object.onceWrapper (node:events:642:26)
at ClientRequest.emit (node:events:527:28)
at TLSSocket.socketErrorListener (node:_http_client:454:9)
at TLSSocket.emit (node:events:527:28)
at emitErrorNT (node:internal/streams/destroy:157:8)
at emitErrorCloseNT (node:internal/streams/destroy:122:3)
at processTicksAndRejections (node:internal/process/task_queues:83:21) {
code: 'ECONNRESET',
host: 'nn.oimi.space',
hostname: 'nn.oimi.space',
method: 'GET',
path: '/https://github.com/helson-lin/ffandown-front/releases/download/v0.0.7/ffandown-frontend.zip',
protocol: 'https:',
url: 'https://nn.oimi.space/https://github.com/helson-lin/ffandown-front/releases/download/v0.0.7/ffandown-frontend.zip'
}
docker启动报错 是访问这个加速地址访问不到吗
