### ISSUE TITLE
在5.0分支源码启动报错

### ISSUE THREAD

**Issue by DingQi1888** [helson-lin/ffandown#43]
在5.0分支源码启动报错  npm run dev   研究了好一会看起来是sqllist部分的问题  但是没找到切入点  大佬帮忙分析指导下

[nodemon] 3.1.4
[nodemon] to restart at any time, enter `rs`
[nodemon] watching path(s): bin\**\*
[nodemon] watching extensions: js
[nodemon] starting `node bootstrap.js`
███████╗███████╗ █████╗ ███╗   ██╗██████╗  ██████╗ ██╗    ██╗███╗   ██╗
██╔════╝██╔════╝██╔══██╗████╗  ██║██╔══██╗██╔═══██╗██║    ██║████╗  ██║
█████╗  █████╗  ███████║██╔██╗ ██║██║  ██║██║   ██║██║ █╗ ██║██╔██╗ ██║
██╔══╝  ██╔══╝  ██╔══██║██║╚██╗██║██║  ██║██║   ██║██║███╗██║██║╚██╗██║
██║     ██║     ██║  ██║██║ ╚████║██████╔╝╚██████╔╝╚███╔███╔╝██║ ╚████║
╚═╝     ╚═╝     ╚═╝  ╚═╝╚═╝  ╚═══╝╚═════╝  ╚═════╝  ╚══╝╚══╝ ╚═╝  ╚═══╝

download and set env failed:HTTPError: Response code 404 (Not Found)
download and set env failed:HTTPError: Response code 404 (Not Found)
[ffandown] Database synced successfully
node:internal/process/promises:288
            triggerUncaughtException(err, true /* fromPromise */);
            ^

Error
    at Database.<anonymous> (E:\ffcode\ffandown\node_modules\sequelize\lib\dialects\sqlite\query.js:185:27)
    at E:\ffcode\ffandown\node_modules\sequelize\lib\dialects\sqlite\query.js:183:50
    at new Promise (<anonymous>)
    at Query.run (E:\ffcode\ffandown\node_modules\sequelize\lib\dialects\sqlite\query.js:183:12)
    at E:\ffcode\ffandown\node_modules\sequelize\lib\sequelize.js:315:28
    at async SQLiteQueryInterface.select (E:\ffcode\ffandown\node_modules\sequelize\lib\dialects\abstract\query-interface.js:407:12)
    at async sys_download.findAll (E:\ffcode\ffandown\node_modules\sequelize\lib\model.js:1140:21)
    at async Object.queryMissionByType (E:\ffcode\ffandown\node_modules\oimi-helper\src\sql\index.js:87:33)
    at async Oimi.initalMission (E:\ffcode\ffandown\node_modules\oimi-helper\src\index.js:150:29) {
  name: 'SequelizeDatabaseError',
  parent: [Error: SQLITE_ERROR: no such column: referer] {
    errno: 1,
    code: 'SQLITE_ERROR',
    sql: "SELECT `uid`, `name`, `url`, `useragent`, `referer`, `audioUrl`, `percent`, `filePath`, `speed`, `timemark`, `size`, `status`, `message`, `crt_tm`, `upd_tm` FROM `sys_download` AS `sys_download` WHERE `sys_download`.`status` IN ('0', '1', '2', '5') ORDER BY `sys_download`.`crt_tm` ASC;"
  },
  original: [Error: SQLITE_ERROR: no such column: referer] {
    errno: 1,
    code: 'SQLITE_ERROR',
    sql: "SELECT `uid`, `name`, `url`, `useragent`, `referer`, `audioUrl`, `percent`, `filePath`, `speed`, `timemark`, `size`, `status`, `message`, `crt_tm`, `upd_tm` FROM `sys_download` AS `sys_download` WHERE `sys_download`.`status` IN ('0', '1', '2', '5') ORDER BY `sys_download`.`crt_tm` ASC;"
  },
  sql: "SELECT `uid`, `name`, `url`, `useragent`, `referer`, `audioUrl`, `percent`, `filePath`, `speed`, `timemark`, `size`, `status`, `message`, `crt_tm`, `upd_tm` FROM `sys_download` AS `sys_download` WHERE `sys_download`.`status` IN ('0', '1', '2', '5') ORDER BY `sys_download`.`crt_tm` ASC;",
  parameters: {}
}

Node.js v18.16.0

**Comment by DingQi1888** [comment]
node_sqlite3.node  放在同级目录也没效果   看起来是oimi框架的启动有问题

**Comment by helson-lin** [comment]
项目下载依赖ffmpeg 报错了 我晚点看下

---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 发送日期 | 2024年08月02日 11:46 |
| 收件人 | helson-lin/ffandown ***@***.***> |
| 抄送人 | Subscribed ***@***.***> |
| 主题 | Re: [helson-lin/ffandown] 在5.0分支源码启动报错 (Issue #43) |

node_sqlite3.node 放在同级目录也没效果 看起来是oimi框架的启动有问题

**Comment by helson-lin** [comment]
你可以先 ping一下https://ipera.oimi.space/ 看不能通，
