### ISSUE TITLE
ffandown-windows-x64. v5.1.0-Beta.exe Windows 10 不能 运行 ，直接打开闪退。

### ISSUE THREAD

**Issue by yijunhong666** [helson-lin/ffandown#59]
ffandown-windows-x64. v5.1.0-Beta.exe Windows 10 不能 运行 ，直接打开闪退。在CMD 命令 打开 提示如图所示 错误。
download and set env failed:TypeError: Invalid host defined options
[ffandown] Database synced successfully
TypeError: Invalid host defined options
    at autoUpdateFrontEnd (C:\snapshot\ffandown\bin\utils\version.js:92:17)
    at initializeFrontEnd (C:\snapshot\ffandown\bin\utils\version.js:124:24)
    at Server.<anonymous> (C:\snapshot\ffandown\bin\app.js:232:19)
    at Object.onceWrapper (node:events:651:28)
    at Server.emit (node:events:549:35)
    at emitListeningNT (node:net:1456:10)
    at process.processTicksAndRejections (node:internal/process/task_queues:81:21)
请问怎么解决呢？
![I_A3E42G99D969~L@{Y74_J](https://github.com/user-attachments/assets/63b81ab0-ceac-423c-bede-ed68bdc04ced)

**Comment by helson-lin** [comment]
没有科学网络下载失败了

---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 发送日期 | 2024年12月24日 18:16 |
| 收件人 | helson-lin/ffandown ***@***.***> |
| 抄送人 | Subscribed ***@***.***> |
| 主题 | [helson-lin/ffandown] ffandown-windows-x64. v5.1.0-Beta.exe Windows 10 不能 运行 ，直接打开闪退。 (Issue #59) |

ffandown-windows-x64. v5.1.0-Beta.exe Windows 10 不能 运行 ，直接打开闪退。在CMD 命令 打开 提示如图所示 错误。
download and set env failed:TypeError: Invalid host defined options
[ffandown] Database synced successfully
TypeError: Invalid host defined options
at autoUpdateFrontEnd (C:\snapshot\ffandown\bin\utils\version.js:92:17)
at initializeFrontEnd (C:\snapshot\ffandown\bin\utils\version.js:124:24)
at Server. (C:\snapshot\ffandown\bin\app.js:232:19)
at Object.onceWrapper (node:events:651:28)
at Server.emit (node:events:549:35)
at emitListeningNT (node:net:1456:10)
at process.processTicksAndRejections (node:internal/process/task_queues:81:21)
请问怎么解决呢？
***@***.***_J.png (view on web)

**Comment by helson-lin** [comment]
需要手动下载依赖和前端文件

---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 发送日期 | 2024年12月24日 18:16 |
| 收件人 | helson-lin/ffandown ***@***.***> |
| 抄送人 | Subscribed ***@***.***> |
| 主题 | [helson-lin/ffandown] ffandown-windows-x64. v5.1.0-Beta.exe Windows 10 不能 运行 ，直接打开闪退。 (Issue #59) |

ffandown-windows-x64. v5.1.0-Beta.exe Windows 10 不能 运行 ，直接打开闪退。在CMD 命令 打开 提示如图所示 错误。
download and set env failed:TypeError: Invalid host defined options
[ffandown] Database synced successfully
TypeError: Invalid host defined options
at autoUpdateFrontEnd (C:\snapshot\ffandown\bin\utils\version.js:92:17)
at initializeFrontEnd (C:\snapshot\ffandown\bin\utils\version.js:124:24)
at Server. (C:\snapshot\ffandown\bin\app.js:232:19)
at Object.onceWrapper (node:events:651:28)
at Server.emit (node:events:549:35)
at emitListeningNT (node:net:1456:10)
at process.processTicksAndRejections (node:internal/process/task_queues:81:21)
请问怎么解决呢？
***@***.***_J.png (view on web)

**Comment by helson-lin** [comment]
https://ffandown.oimi.space/qa.html

---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 发送日期 | 2024年12月24日 18:16 |
| 收件人 | helson-lin/ffandown ***@***.***> |
| 抄送人 | Subscribed ***@***.***> |
| 主题 | [helson-lin/ffandown] ffandown-windows-x64. v5.1.0-Beta.exe Windows 10 不能 运行 ，直接打开闪退。 (Issue #59) |

ffandown-windows-x64. v5.1.0-Beta.exe Windows 10 不能 运行 ，直接打开闪退。在CMD 命令 打开 提示如图所示 错误。
download and set env failed:TypeError: Invalid host defined options
[ffandown] Database synced successfully
TypeError: Invalid host defined options
at autoUpdateFrontEnd (C:\snapshot\ffandown\bin\utils\version.js:92:17)
at initializeFrontEnd (C:\snapshot\ffandown\bin\utils\version.js:124:24)
at Server. (C:\snapshot\ffandown\bin\app.js:232:19)
at Object.onceWrapper (node:events:651:28)
at Server.emit (node:events:549:35)
at emitListeningNT (node:net:1456:10)
at process.processTicksAndRejections (node:internal/process/task_queues:81:21)
请问怎么解决呢？
***@***.***_J.png (view on web)

**Comment by yijunhong666** [comment]
![QQ截图20241227175535](https://github.com/user-attachments/assets/8970e844-d7ae-4b7e-9624-b4d9871404ce)

已经按照教程安装成功了，现在Windows 版本的 也能 正常启动了，非常感谢。

**Comment by helson-lin** [comment]
Ffmpeg/ffprobe 都下载了吧，建议测试一下功能是否正常，下个版本将修改掉 github api 为国内的接口，文件托管也会修改，就不会存在这个问题了


---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 发送日期 | 2024年12月27日 17:56 |
| 收件人 | ***@***.***> |
| 抄送人 | ***@***.***> ,
***@***.***> |
| 主题 | Re: [helson-lin/ffandown] ffandown-windows-x64. v5.1.0-Beta.exe Windows 10 不能 运行 ，直接打开闪退。 (Issue #59) |

QQ.20241227175535.png (view on web)

已经按照教程安装成功了，现在Windows 版本的 也能 正常启动了，非常感谢。

**Comment by helson-lin** [comment]
没啥问题 issue 关闭了
